- inc/drivers/HIDMouse.h
- source/drivers/HIDJoystick.cpp
left and middle mouse button enum was backwards and I had fixed some joystick stuff a while ago that I forgot to push.
> DM: fix mouse enum and some joystick fixes I forgot to commit

- source/driver-models/CodalUSB.cpp
this allows us to use HID keyboard and stuff with iOS which wants a max of 100mA current draw.
> DM: update USB max power to 100mA for mobile

- inc/core/CodalFiber.h
- source/core/CodalFiber.cpp
I used to keep back-pointer to codal fiber from my user data, and list on my side, but this doesn't work with FOB, since the fiber pointer changes.
Thus, I need to get the list of fibers directly from Codal.
I also refactored the FOB handling to a function, and prevented usage of FOB and user_data at the same time (it breaks).
> Add codal::list_fibers() API; prevent FOB when user_data set

- inc/JACDAC/JDProtocol.h
- source/JACDAC/JDDriver.cpp
- source/JACDAC/JDLogicDriver.cpp
- source/JACDAC/JDProtocol.cpp
@pelikhan @teddyseyed @mmoskal 
This PR introduces a new control packet type: `ERROR`. It also adds a new interface to a JDDriver `handleErrorPacket`, which is invoked when a control packet flagging an error is received.
Error codes are automatically placed into control packets by the logic driver based on the JDDevice state in a driver. To set an error code call `driver.device.setError(ERR_CODE)`. Protocol error codes are limited to 16 numbers (4 bits), time will tell if this is enough error codes...
JDProtocol now accepts a debugging name that is placed in the control packet when an error is flagged: `JDProtocol::setDebugName`, you can also retrieve the current debug name using `JDProtocol::getDebugName`. Currently it's one debug name per device, rather than per driver. I might take it …
> Jacdac protocol errors

- inc/core/CodalHeapAllocator.h
- source/core/CodalFiber.cpp
- source/core/CodalHeapAllocator.cpp
* prefix `malloc()`, `free()`, and `realloc()` with `device_*`
* define the plain versions as weak aliases of  `device_*` versions
* make sure `currentFiber` is set properly when calling memory allocator from the stack verification routine
* bugfix in `calloc()`
* limit number of fibers in the pool to 3
This lets me re-define `malloc()` to use the same heap as my GC. I still direct allocations in ISR to `device_malloc()`. This follows @finneyj suggestion of a separate heap for ISRs - my GC allocates most of the Codal's heap for its own heap and what's left is the "ISR heap". The ISR is also used for temporary structures of the GC.
> allow for plugging in an external memory allocator

- inc/driver-models/Serial.h
- source/driver-models/Serial.cpp
Now, a developer only is required to implement the following functions:
```cpp
virtual int enableInterrupt(SerialInterruptType t);
virtual int disableInterrupt(SerialInterruptType t);
virtual int setBaudrate(uint32_t baudrate);
virtual int configurePins(Pin& tx, Pin& rx);
virtual int putc(char);
virtual int getc();
```
(and obviously the constructor)
An implementation of this can be seen [in this commit](https://github.com/lancaster-university/codal-samd/pull/3/commits/04b5dc475fbecb31bde53534a9143c2ee8f2dcd1).
> Refactor Serial Class

- inc/driver-models/LowLevelTimer.h
This will be used for dedicated timer scenarios where precise interrupts are required.
For visibility.
> add First draft of low-level timer

- inc/JACDAC/JDProtocol.h
- source/JACDAC/JDDriver.cpp
- source/JACDAC/JDLogicDriver.cpp
- source/JACDAC/JDProtocol.cpp
The logic driver ignored disconnect / connect events for broadcast drivers. There was also a risk that by connecting and disconnecting broadcast drivers from the bus, you could crash a jacdac device.
cc @pelikhan 
Just need to test.
> Apply patch for broadcast driver disconnection

- inc/drivers/MMA8453.h
Adds support for MMA8453 accelerometer. As far as what we're doing, it's the same as the existing MMA8653, except for the address and whoami.
It's in BrainPad and BrainPad Arcade (tested in Arcade)
> Add MMA8453

- inc/drivers/ILI9341.h
- inc/drivers/ST7735.h
- source/drivers/ILI9341.cpp
- source/drivers/ST7735.cpp
The screen is very similar to st7735, except for:
* init sequence
* no support for 12 bit color; we use 16 bit
* the driver currently assumes we want 2x scaled images, which keeps the resolution similar to ST7735
> Add support for ILI9341 screen

- inc/driver-models/CodalUSB.h
- source/driver-models/CodalUSB.cpp
This was originally set here: https://github.com/lancaster-university/codal-core/pull/32
I broke it later: https://github.com/lancaster-university/codal-core/commit/36dafe77219239c1397ece44ed37a7f6e6f50d5a
I guess the problem is that CPX can indeed draw more than 100mA, but I guess we'll just take the chances. Making it configurable, but PXT will keep the new 100mA default.
Original issue: https://github.com/microsoft/pxt-adafruit/issues/837
Current issue: https://forum.makecode.com/t/circuit-playground-express-on-mobile-devices/799
> Set defualt USB current to 100mA and allow for changes

- inc/driver-models/NVMController.h
- inc/drivers/KeyValueStorage.h
- source/drivers/KeyValueStorage.cpp
@jamesadevine  
Please see 
- changes to your interface here to make it compatible with on chip and off chip storage
- updates to KeyValueStorage to not assume memory is in MCU address space
This will mean some minor revs to anything using this interface. Is that OK>
> Off chip storage

- inc/core/CodalHeapAllocator.h
- inc/streams/DataStream.h
- inc/streams/Mixer.h
- inc/types/ManagedString.h
- source/core/CodalFiber.cpp
- source/core/CodalHeapAllocator.cpp
- source/streams/DataStream.cpp
- source/types/ManagedString.cpp
This pull-request converts the misspelling `availiable` to the correct `available`.
> Fixed typo: availiable -> available

- inc/core/codal_target_hal.h
- inc/driver-models/Timer.h
- source/core/CodalDmesg.cpp
- source/core/CodalFiber.cpp
- source/core/CodalHeapAllocator.cpp
- source/core/codal_default_target_hal.cpp
- source/driver-models/Timer.cpp
- source/drivers/HIDKeyboard.cpp
- source/drivers/LEDMatrix.cpp
- source/drivers/MessageBus.cpp
This is needed by RP2040 - the flash is external any function calls into flash typically involve 20us+ latency (which increases the more code you run).
While this is quite ugly, the real ugly bit is in codal-rp2040 where I had to copy a bunch of SDK functions since they do not have these attributes...
> Add REAL_TIME_FUNC attribute

- inc/core/codal_target_hal.h
FORCE_RAM_FUNC now correctly uses .data.ramfuncs rather than plain .data, to work with newer gcc versions. See issue #33 at https://github.com/lancaster-university/microbit-v2-samples/issues/33
> Fix for problems compiling on gcc 10.3.x+

- inc/core/CodalComponent.h
- inc/streams/LevelDetector.h
- inc/streams/LevelDetectorSPL.h
- inc/streams/StreamSplitter.h
- source/streams/LevelDetector.cpp
- source/streams/LevelDetectorSPL.cpp
- source/streams/StreamSplitter.cpp
Ready for review or merge into new branch
Introduced 'stream splitter' which takes the mic input after coming through the processor and distributes it to many downstream consumers. This allows other downstream code to connect to the mic input easily, modualr way without having to the up the pipeline themselves.
Additionally level detector and level detector SPL now have an initilised instance in uBit and so can be accessed globally in user code - special parameters have been added to their constructors so that they can be inisilised but dont start up untill they are needed to prevent the mic starting up when uBit starts.
Matches pull requests on codal-microbit-v2 and codal nrf-52 with the same name
> Input Pipeline

- source/driver-models/Serial.cpp
This PR alters ASYNC serial send behaviour to now deschedule the current fiber for zero ticks if the txbuffer is full to allow the hardware to drain.
The previous behaviour would effectively truncate the buffer instead; see this bug: https://github.com/lancaster-university/codal-microbit-v2/issues/149
> Fix for Serial ASYNC mode incorrectly truncating buffers

- inc/core/ErrorNo.h
Removed as its never used, and repurposed it for the base error address DEVICE_PERIPHERAL_ERROR, from which on-board periperhal errors can be numbered, as required, for implementing boards.
The Micro:bit v2, for example now has a `MicroBitPanic` enum with `ACCELEROMETER_ERROR = PanicCode::DEVICE_PERIPHERAL_ERROR + 1, // Aka. Panic 51` available for device specific peripheral errors.
Note: the entire 50->59 space is available for board-specific errors.
See also:
- https://github.com/lancaster-university/codal-microbit-v2/issues/213
- https://github.com/lancaster-university/codal-microbit-v2/issues/191
> Removed and repurposed DEVICE_USB_ERROR

- inc/core/CodalFiber.h
- inc/driver-models/Serial.h
- source/core/CodalFiber.cpp
- source/driver-models/Serial.cpp
Adds a semaphore mode to the FiberLock, for limited multiple access as a prelude to power control.
This needs testing before we can merge it in, but it _should_ have no effect on anything, as the default remains a mutex.
> Enhanced FiberLock to include semaphore operations

- source/driver-models/Serial.cpp
In line with the discussion in the `codal-microbit-v2` issue here: https://github.com/lancaster-university/codal-microbit-v2/issues/179
> Enforced serial RX pullup on a redirect, to match micro:bit v1.xx behaviour

- inc/core/CodalComponent.h
- inc/driver-models/I2C.h
- inc/driver-models/Pin.h
- inc/driver-models/PinPeripheral.h
- inc/driver-models/SPI.h
- inc/driver-models/Serial.h
- inc/driver-models/SingleWireSerial.h
- inc/drivers/Button.h
- inc/drivers/PulseIn.h
- inc/drivers/TouchButton.h
- source/driver-models/I2C.cpp
- source/driver-models/PinPeripheral.cpp
- source/driver-models/SPI.cpp
- source/driver-models/Serial.cpp
- source/driver-models/Timer.cpp
- source/drivers/Button.cpp
- source/drivers/PulseIn.cpp
- source/drivers/TouchButton.cpp
- source/drivers/TouchSensor.cpp
Introduces cleaner and more scalable interface for dynamic management of how pins are bound to peripherals.
In short, provides the necessary plumbing to enable targets to track which pins are used by which peripherals, and more consistently connect/disconnect and reuse pins at run time. Provides necessary groundwork to resolve issues such as: https://github.com/lancaster-university/codal-microbit-v2/issues/226
Summary of changes:
- Introduce PinPeriheral interface, with well defined methods for locking and requesting the release of a peripheral's pin resources.
- Updates to Pin interface, to more explicitly control runtime connection and disconnection of pins from peripherals.
- Addition of redirect() methods for SPI and I2C base classes (and making associated variables mutable pointers …
> Dynamic pin peripherals

- source/drivers/AnimatedDisplay.cpp
Update to the internal  AnimatedDisplay::waitForFreeDisplay() method to ensure that fibers queued waiting for access to the display always re-contest for access, thereby avoiding potential race conditions.
> Ensure AnimatedDisplay::waitForFreeDisplay() is free of race conditions

- inc/core/CodalConfig.h
The value in `DEVICE_DMESG_BUFFER_SIZE` configures if the debug messages log/buffer is compiled or not.
Currently the only way not to compile the debug buffer is by setting `DEVICE_DMESG_BUFFER_SIZE` to 0, either in codal.json on the target.json files. This is non-obvious and not documented anywhere:
- https://github.com/lancaster-university/codal-microbit-v2/issues/297
Currently `DEVICE_DMESG` doesn't do anything:
- https://github.com/lancaster-university/codal-microbit-v2/issues/296
We normally use `DMESG_SERIAL_DEBUG` to enable debug data to be printed to serial, but there is also a use-case of having the debug log/buffer in RAM to be able to access it via debugger. `DEVICE_DMESG` should probably be used to enable/disable the debug log, and additionally `DMESG_SERIAL_DEBUG` would be …
> Set default DEVICE_DMESG_BUFFER_SIZE based on DEVICE_DMESG.

- source/driver-models/Compass.cpp
Fixes recalibration.
See https://github.com/lancaster-university/codal-microbit-v2/issues/286#issuecomment-1484243324
> Compass::clearCalibration() resets calibration member variable

- inc/core/gcc_compat.h
- source/core/gcc_compat.cpp
> Added a set of C function hooks to patch holes in the Newlib API to squash the GCC v12+ warnings.
This adds the missing functions that gcc-11 and gcc-12 seem to want despite being in -lnosys mode. The warnings don't break the build, but cause a smattering of errors throughout.
> gcc 12.x.x compatibility functions - newlib support

- inc/driver-models/NVMController.h
This saves about 184 bytes of flash with gcc v10.3.1 & the codal-microbit-v2 build configuration.
And, as it might be removing the entry in the vtable for the derived classes, it could be a bit more efficient too.
Related to:
- https://github.com/lancaster-university/codal-core/pull/162
- https://github.com/lancaster-university/codal-core/pull/163
> Make all methods in `NVMController` pure virtual.

- inc/driver-models/AbstractButton.h
- source/driver-models/AbstractButton.cpp
This saves about 40 bytes of flash with gcc v10.3.1 & the codal-microbit-v2 build configuration.
And, as it might be removing the entry in the vtable for the derived classes, it could be a bit more efficient too.
Related to:
- https://github.com/lancaster-university/codal-core/pull/162
- https://github.com/lancaster-university/codal-core/pull/164
> Make `AbstractButton::isPressed()` pure virtual.

- inc/core/codal_target_hal.h
- source/core/codal_default_target_hal.cpp
__sync_fetch_and_add_2() is a clang builtin, do not declare this function separately when building with clang.
> [Clang compatibility] Preprocessor Directives to ignore builtin clang function

- inc/streams/LevelDetector.h
- inc/streams/LevelDetectorSPL.h
Adds a bit more info about units, and what happens when thresholds are set in the opposite direction (high<low).
> Update docstrings for LevelDetector threshold methods.

- source/drivers/AnimatedDisplay.cpp
Currently it was scrolling a NULL pointer:
- https://github.com/lancaster-university/codal-microbit-v2/issues/423
This matches the V1 and MakeCode sim behaviour.
> Display scroll an empty char if the requested char is out-of-range. 

- inc/driver-models/Pin.h
- inc/types/Matrix4.h
- source/driver-models/CodalUSB.cpp
- source/types/Matrix4.cpp
And ensures header files declare new classes in the codal namespace.
This is part of:
- https://github.com/lancaster-university/codal-microbit-v2/issues/240
Haven't touched the CodalUSB.h header file to declare its classes inside the codal namespace, as this file is not used by the codal-microbit-v2 target and could affect other targets using it.
> Ensure .cpp files are `using namespace codal`.

- inc/core/CodalConfig.h
Flag mostly to be used in other CODAL libraries/targets.
This is part of:
- https://github.com/lancaster-university/codal-microbit-v2/issues/240
As removing 'using namespace codal' from `codal-nrf52` can break a few targets, this patch adds a CODAL flag/macro to enable/disable its usage.
> Add config flag to enable/disable adding codal to the global namespace.

- inc/streams/StreamRecording.h
- source/streams/StreamRecording.cpp
WORK IN PROGRESS - DO NOT MERGE
Possible workaround for https://github.com/lancaster-university/codal-microbit-v2/issues/450.
Adds a variable to shadow totalBufferLength, and accumulate the memory overhead of adding each buffer. The limit is then the total memory usage, rather than totalBufferLength.
Adjusts maxBufferLength, so the default case with 256 byte buffers still records the same amount of data.
> StreamRecording - calculate memory overhead of buffers

- source/driver-models/Accelerometer.cpp
- source/driver-models/Compass.cpp
- source/streams/LevelDetectorSPL.cpp
- source/streams/StreamNormalizer.cpp
- source/streams/Synthesizer.cpp
Specifically for `LevelDetectorSPL::pullRequest()`, as float in the micro:bit's Cortex-M4f is much faster and this function runs a lot in the background.
Related PR:
- https://github.com/lancaster-university/codal-microbit-v2/pull/454
> Ensure float literals and float versions of math functions are used.

- inc/core/codal_target_hal.h
This is for the LLVM build, as it doesn't support `long_call` attribute for ARM: https://github.com/llvm/llvm-project/issues/39969
> Update FORCE_RAM_FUNC  macro attributes to be compiler-specific.
